/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface CertificateRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "getCertificate"
      | "getCertificateCount"
      | "isCertificateRegistered"
      | "owner"
      | "registerCertificate"
      | "renounceOwnership"
      | "revokeCertificate"
      | "transferOwnership"
      | "verifyCertificate"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "CertificateRegistered"
      | "CertificateRevoked"
      | "OwnershipTransferred"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "getCertificate",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getCertificateCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "isCertificateRegistered",
    values: [string]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "registerCertificate",
    values: [string, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "revokeCertificate",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "verifyCertificate",
    values: [string, BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "getCertificate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCertificateCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isCertificateRegistered",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "registerCertificate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "revokeCertificate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifyCertificate",
    data: BytesLike
  ): Result;
}

export namespace CertificateRegisteredEvent {
  export type InputTuple = [
    certificateId: string,
    certificateHash: BytesLike,
    issuer: AddressLike,
    registeredAt: BigNumberish
  ];
  export type OutputTuple = [
    certificateId: string,
    certificateHash: string,
    issuer: string,
    registeredAt: bigint
  ];
  export interface OutputObject {
    certificateId: string;
    certificateHash: string;
    issuer: string;
    registeredAt: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CertificateRevokedEvent {
  export type InputTuple = [
    certificateId: string,
    certificateHash: BytesLike,
    reason: string,
    revokedAt: BigNumberish
  ];
  export type OutputTuple = [
    certificateId: string,
    certificateHash: string,
    reason: string,
    revokedAt: bigint
  ];
  export interface OutputObject {
    certificateId: string;
    certificateHash: string;
    reason: string;
    revokedAt: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface CertificateRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): CertificateRegistry;
  waitForDeployment(): Promise<this>;

  interface: CertificateRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getCertificate: TypedContractMethod<
    [certificateId: string],
    [
      [string, string, string, bigint, boolean, bigint, string] & {
        id: string;
        certificateHash: string;
        issuer: string;
        registeredAt: bigint;
        revoked: boolean;
        revokedAt: bigint;
        revocationReason: string;
      }
    ],
    "view"
  >;

  getCertificateCount: TypedContractMethod<[], [bigint], "view">;

  isCertificateRegistered: TypedContractMethod<
    [certificateId: string],
    [boolean],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  registerCertificate: TypedContractMethod<
    [certificateId: string, certificateHash: BytesLike],
    [void],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  revokeCertificate: TypedContractMethod<
    [certificateId: string, reason: string],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  verifyCertificate: TypedContractMethod<
    [certificateId: string, certificateHash: BytesLike],
    [[boolean, boolean] & { isValid: boolean; isRevoked: boolean }],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getCertificate"
  ): TypedContractMethod<
    [certificateId: string],
    [
      [string, string, string, bigint, boolean, bigint, string] & {
        id: string;
        certificateHash: string;
        issuer: string;
        registeredAt: bigint;
        revoked: boolean;
        revokedAt: bigint;
        revocationReason: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getCertificateCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "isCertificateRegistered"
  ): TypedContractMethod<[certificateId: string], [boolean], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "registerCertificate"
  ): TypedContractMethod<
    [certificateId: string, certificateHash: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "revokeCertificate"
  ): TypedContractMethod<
    [certificateId: string, reason: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "verifyCertificate"
  ): TypedContractMethod<
    [certificateId: string, certificateHash: BytesLike],
    [[boolean, boolean] & { isValid: boolean; isRevoked: boolean }],
    "view"
  >;

  getEvent(
    key: "CertificateRegistered"
  ): TypedContractEvent<
    CertificateRegisteredEvent.InputTuple,
    CertificateRegisteredEvent.OutputTuple,
    CertificateRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "CertificateRevoked"
  ): TypedContractEvent<
    CertificateRevokedEvent.InputTuple,
    CertificateRevokedEvent.OutputTuple,
    CertificateRevokedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;

  filters: {
    "CertificateRegistered(string,bytes32,address,uint256)": TypedContractEvent<
      CertificateRegisteredEvent.InputTuple,
      CertificateRegisteredEvent.OutputTuple,
      CertificateRegisteredEvent.OutputObject
    >;
    CertificateRegistered: TypedContractEvent<
      CertificateRegisteredEvent.InputTuple,
      CertificateRegisteredEvent.OutputTuple,
      CertificateRegisteredEvent.OutputObject
    >;

    "CertificateRevoked(string,bytes32,string,uint256)": TypedContractEvent<
      CertificateRevokedEvent.InputTuple,
      CertificateRevokedEvent.OutputTuple,
      CertificateRevokedEvent.OutputObject
    >;
    CertificateRevoked: TypedContractEvent<
      CertificateRevokedEvent.InputTuple,
      CertificateRevokedEvent.OutputTuple,
      CertificateRevokedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
  };
}
